;-------------------------project settings------------------------------;
[project]
atlas_name=maastricht (INVULLEN)
supplier=ruben.vanderzaag (INVULLEN)
layer_collection=maastricht_klimaatatlas (INVULLEN)
organisation_uuid=14e8cc7b-a88a-44b4-8d5b-c800b7622aeb (INVULLEN)

;-------------------------login settings------------------------------;
[lizard]
username=__key__
password=INVULLEN

